"""Generate fhir/input/fsh/stream-check-questions.fsh from data/questions.json.

One code per stream-check answer key (per-margin sections get a left and a right
code), so the exporter can use the answer key itself as the component code.
Run again whenever data/questions.json changes; a pytest checks they agree.

Usage: python fhir/scripts/gen_question_codes.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
QUESTIONS = ROOT / "data" / "questions.json"
OUT = ROOT / "fhir" / "input" / "fsh" / "stream-check-questions.fsh"


def answer_keys(section: dict) -> list[tuple[str, str]]:
    """(key, display) for every answer key of a section, matching web/src/lib/checkin.ts answerKeys()."""
    out = []
    for margin in section.get("per_margin") or [None]:
        for q in section["questions"]:
            if margin is None:
                out.append((q["id"], q["label"]))
            else:
                prefix, rest = q["id"].split("_", 1)
                out.append((f"{prefix}_{margin}_{rest}", f"{q['label']} ({margin} bank)"))
    return out


def fsh_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(questions: dict) -> str:
    lines = [
        "// Generated by fhir/scripts/gen_question_codes.py from data/questions.json. Do not edit by hand.",
        "CodeSystem: AquaSentinelStreamCheckQuestions",
        "Id: aquasentinel-stream-check",
        'Title: "AquaSentinel stream check questions"',
        'Description: "One code per stream-check answer key. Questions follow Annex I of the OneAquaHealth field sampling protocol '
        '(https://doi.org/10.5281/zenodo.20344421); the water_signs section is an AquaSentinel addition aligned with the OAH code foam."',
        "* ^experimental = true",
        "* ^caseSensitive = true",
    ]
    for section in questions["sections"]:
        for key, display in answer_keys(section):
            lines.append(f'* #{key} "{fsh_string(display)}"')
    return "\n".join(lines) + "\n"


def main() -> None:
    questions = json.loads(QUESTIONS.read_text(encoding="utf-8"))
    OUT.write_text(render(questions), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
