#!/usr/bin/env bash
# Prepare everything the FHIR build and validation need, once:
#   1. the HL7 validator jar in tools/ (gitignored)
#   2. the OAH IG source at a pinned commit in fhir/.oah-ig/ (gitignored; the repo has no LICENSE, so we never copy it into ours)
#   3. a local FHIR package hl7.eu.fhir.oah#0.1.0-ci-build built from that source with SUSHI,
#      with snapshots generated by the validator, installed into ~/.fhir/packages
# After the first run everything is cached and the build works offline.
# Set FORCE_OAH=1 to rebuild the OAH package.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

VALIDATOR_VERSION="${VALIDATOR_VERSION:-6.10.4}"
VALIDATOR_JAR="tools/validator_cli.jar"
VALIDATOR_URL="https://github.com/hapifhir/org.hl7.fhir.core/releases/download/${VALIDATOR_VERSION}/validator_cli.jar"
OAH_REPO="https://github.com/hl7-eu/oah"
OAH_COMMIT="b907cf0869b59d82d9138b3d147fca66f333d911"
OAH_DIR="fhir/.oah-ig"
OAH_PKG_DIR="$OAH_DIR/local-package"
OAH_CACHE="$HOME/.fhir/packages/hl7.eu.fhir.oah#0.1.0-ci-build"
PYTHON="${PYTHON:-.venv/bin/python}"
[ -x "$PYTHON" ] || PYTHON=python3

log() { printf '[setup_oah] %s\n' "$*"; }

ensure_validator() {
  if [ -s "$VALIDATOR_JAR" ] && [ -f "tools/validator_cli.version" ] && [ "$(cat tools/validator_cli.version)" = "$VALIDATOR_VERSION" ]; then
    return
  fi
  mkdir -p tools
  log "downloading HL7 validator $VALIDATOR_VERSION"
  if ! curl -fsSL --retry 3 -o "$VALIDATOR_JAR.part" "$VALIDATOR_URL"; then
    # github.com release downloads sometimes answer HTTP 500; the GitHub CLI uses the API instead.
    if command -v gh >/dev/null 2>&1; then
      log "direct download failed; trying the GitHub CLI"
      rm -f "$VALIDATOR_JAR.part"
      gh release download "$VALIDATOR_VERSION" -R hapifhir/org.hl7.fhir.core -p validator_cli.jar -O "$VALIDATOR_JAR.part"
    else
      log "could not download $VALIDATOR_URL"; exit 1
    fi
  fi
  mv "$VALIDATOR_JAR.part" "$VALIDATOR_JAR"
  echo "$VALIDATOR_VERSION" > tools/validator_cli.version
}

ensure_oah_source() {
  if [ ! -d "$OAH_DIR/.git" ]; then
    log "cloning $OAH_REPO"
    git clone -q "$OAH_REPO" "$OAH_DIR"
  fi
  if [ "$(git -C "$OAH_DIR" rev-parse HEAD)" != "$OAH_COMMIT" ]; then
    git -C "$OAH_DIR" fetch -q origin "$OAH_COMMIT" || true
    git -C "$OAH_DIR" checkout -q "$OAH_COMMIT"
    rm -rf "$OAH_DIR/fsh-generated" "$OAH_PKG_DIR"
  fi
}

ensure_oah_package() {
  if [ -z "${FORCE_OAH:-}" ] && [ -f "$OAH_CACHE/package/package.json" ] && [ -f "$OAH_PKG_DIR/.commit" ] \
     && [ "$(cat "$OAH_PKG_DIR/.commit")" = "$OAH_COMMIT" ]; then
    return
  fi
  log "building the OAH IG with SUSHI"
  npx --no-install sushi build "$OAH_DIR" > "$OAH_DIR/sushi.log" 2>&1 || { tail -30 "$OAH_DIR/sushi.log"; exit 1; }
  "$PYTHON" fhir/scripts/build_oah_package.py "$OAH_DIR" "$OAH_PKG_DIR"
  local snap="$OAH_PKG_DIR/snapshots"
  rm -rf "$snap"; mkdir -p "$snap"
  cp "$OAH_PKG_DIR"/package/StructureDefinition-*.json "$snap/"
  log "generating snapshots with the HL7 validator"
  java -jar "$VALIDATOR_JAR" snapshot -version 4.0.1 -tx n/a -ig hl7.fhir.uv.xver-r5.r4#0.1.0 \
    -ig "$OAH_PKG_DIR/package" "$snap"/StructureDefinition-*.json -outputSuffix snapshot.json \
    > "$OAH_PKG_DIR/snapshot.log" 2>&1 || { tail -30 "$OAH_PKG_DIR/snapshot.log"; exit 1; }
  "$PYTHON" fhir/scripts/build_oah_package.py "$OAH_DIR" "$OAH_PKG_DIR" --no-build --snapshots "$snap" --install
  echo "$OAH_COMMIT" > "$OAH_PKG_DIR/.commit"
}

ensure_validator
ensure_oah_source
ensure_oah_package
log "ready: validator $(cat tools/validator_cli.version), OAH commit $OAH_COMMIT"
