"""Turn HL7 validator output into docs/evidence/validation-summary.md and a pass/fail exit code.

Valid records (examples and generated bundles) must have 0 errors. Every negative
record in fhir/negative/manifest.json must fail with at least one error whose
location or message contains its 'expect' text.

Usage: python fhir/scripts/summarise_validation.py <validator-output.json> <summary.md> --meta KEY=VALUE ...
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
NEGATIVE_DIR = ROOT / "fhir" / "negative"
FILE_EXT = "http://hl7.org/fhir/StructureDefinition/operationoutcome-file"


def outcomes(path: Path) -> dict[str, list[dict[str, Any]]]:
    """File path (relative to the repo) -> issues."""
    doc = json.loads(path.read_text(encoding="utf-8"))
    oos = [e["resource"] for e in doc.get("entry", [])] if doc.get("resourceType") == "Bundle" else [doc]
    out: dict[str, list[dict[str, Any]]] = {}
    for oo in oos:
        files = [x.get("valueString") for x in oo.get("extension", []) if x.get("url") == FILE_EXT]
        name = files[0] if files else "(unknown)"
        rel = str(Path(name).resolve().relative_to(ROOT)) if Path(name).resolve().is_relative_to(ROOT) else name
        out[rel] = oo.get("issue", [])
    return out


def count(issues: list[dict[str, Any]], *levels: str) -> int:
    return sum(1 for i in issues if i.get("severity") in levels)


def message(issue: dict[str, Any]) -> str:
    where = ", ".join(issue.get("expression", []) or issue.get("location", []))
    return f"{where}: {issue.get('details', {}).get('text', '')}".strip()


def matches(issue: dict[str, Any], expect: str) -> bool:
    return expect.lower() in message(issue).lower()


def md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def summarise(results: dict[str, list[dict[str, Any]]], meta: dict[str, str]) -> tuple[str, bool]:
    manifest = json.loads((NEGATIVE_DIR / "manifest.json").read_text(encoding="utf-8"))["cases"]
    negatives = {f"fhir/negative/{k}": v for k, v in manifest.items()}
    valid = {k: v for k, v in sorted(results.items()) if k not in negatives}
    ok = True

    lines = ["# FHIR validation summary", "",
             "Generated by `npm run validate` (fhir/scripts/validate.sh). Do not edit by hand.", "",
             "## Tools and inputs", "", "| Item | Value |", "|------|-------|"]
    lines += [f"| {k} | {md_escape(v)} |" for k, v in meta.items()]

    total_err = sum(count(v, "error", "fatal") for v in valid.values())
    total_warn = sum(count(v, "warning") for v in valid.values())
    neg_pass = 0
    neg_rows = []
    for name, case in negatives.items():
        issues = results.get(name)
        if issues is None:
            neg_rows.append(f"| {name} | {md_escape(case['reason'])} | not validated | 0 | FAIL (missing) |")
            ok = False
            continue
        errors = [i for i in issues if i.get("severity") in ("error", "fatal")]
        hit = [i for i in errors if matches(i, case["expect"])]
        passed = bool(hit)
        neg_pass += passed
        ok &= passed
        first = md_escape(message(hit[0] if hit else (errors[0] if errors else {"details": {"text": "no errors"}})))[:220]
        neg_rows.append(f"| {name} | {md_escape(case['reason'])} | {first} | {len(errors)} | {'PASS (rejected as expected)' if passed else 'FAIL'} |")

    valid_rows = []
    for name, issues in valid.items():
        e, w, info = count(issues, "error", "fatal"), count(issues, "warning"), count(issues, "information")
        ok &= e == 0
        valid_rows.append(f"| {name} | {e} | {w} | {info} | {'PASS' if e == 0 else 'FAIL'} |")

    lines += ["", "## Result", "",
              f"- Valid records: {len(valid)} files, {total_err} errors, {total_warn} warnings.",
              f"- Negative tests: {neg_pass} of {len(negatives)} rejected as expected.",
              f"- Overall: **{'PASS' if ok else 'FAIL'}**", "",
              "## Valid records (must have 0 errors)", "",
              "| File | Errors | Warnings | Information | Result |", "|------|--------|----------|-------------|--------|", *valid_rows,
              "", "## Negative tests (must fail)", "",
              "| File | What is broken | First matching error | Errors | Result |", "|------|----------------|----------------------|--------|--------|",
              *neg_rows, "", "## Warnings on valid records", ""]
    warn_kinds: dict[str, int] = {}
    for issues in valid.values():
        for i in issues:
            if i.get("severity") == "warning":
                text = i.get("details", {}).get("text", "")
                key = text.split(" in system ")[0] if "Unable to validate code" in text else text[:160]
                warn_kinds[key] = warn_kinds.get(key, 0) + 1
    if warn_kinds:
        lines += ["| Warning | Count |", "|---------|-------|"]
        lines += [f"| {md_escape(k)} | {v} |" for k, v in sorted(warn_kinds.items(), key=lambda kv: -kv[1])]
    else:
        lines.append("None.")
    lines += ["", "Warnings are explained in fhir/README.md (section Validation)."]
    return "\n".join(lines) + "\n", ok


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("summary", type=Path)
    parser.add_argument("--meta", action="append", default=[], help="KEY=VALUE rows for the tools table")
    args = parser.parse_args()
    meta = dict(item.split("=", 1) for item in args.meta)
    text, ok = summarise(outcomes(args.output), meta)
    args.summary.parent.mkdir(parents=True, exist_ok=True)
    args.summary.write_text(text, encoding="utf-8")
    print(text)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
