// AquaSentinel terminology: only concepts the OAH TemporaryOahSystem does not have.
// OAH codes (diptera, birds, amphibians, hydrology, morophology, foam, macrophytes,
// riparianVegetation, absent/present/extensive, cover classes) are reused as they are.

CodeSystem: AquaSentinelCodes
Id: aquasentinel
Title: "AquaSentinel codes"
Description: "Concepts AquaSentinel needs that the OAH TemporaryOahSystem does not define. No code here describes infection, disease or a diagnosis."
* ^experimental = true
* ^caseSensitive = true
// --- record markers
* #synthetic "Synthetic record" "Generated by the AquaSentinel synthetic scenario. Not a real observation."
// --- what was observed
* #larval-dip-count "Mosquito larvae counted in standard dips" "Total mosquito larvae counted by a volunteer across standard cup dips at one visit."
* #dip-count "Larvae in one dip" "Larvae counted in a single cup dip."
* #larval-posture "Larval resting posture (guided key)" "Resting posture of larvae at the water surface, answered through the AquaSentinel guided key."
* #adult-mosquito-key "Adult mosquito type (guided key)" "Adult mosquito type from the guided key. Never a species identification."
* #bats "Bats" "Bats seen hunting over the stream at dusk."
* #predator-photo "Bird or amphibian photo candidate" "Bird or amphibian in a photo, candidate confirmed by the volunteer."
* #dead-bird-report "Dead bird report (count, place and time only)" "A volunteer saw dead birds. Count, place and time only. No identification, cause of death or diagnosis is made."
* #vector-habitat-risk-index "Vector-habitat risk index" "AquaSentinel index of conditions that favour mosquito vectors near a stream site. It describes habitat, never infection status."
// --- answers and key results
* #angled "Resting at an angle"
* #flat "Lying flat, parallel to the surface"
* #culex_type "Culex-type larva (key result)"
* #anopheles_type "Anopheles-type larva (key result)"
* #larvae_present "Larvae visible in the cup"
* #larvae_absent "No larvae visible in the cup"
* #striped_aedes_type "Black and white striped mosquito (Aedes albopictus-like type)"
* #plain_culex_type "Plain brown mosquito (Culex type)"
* #not_a_mosquito "Not a mosquito"
* #standing_water "Standing water at the edge"
* #flowing_water "Flowing water at the edge"
* #dry_channel "Dry channel"
* #bird_unidentified "A bird, species unclear"
* #amphibian_unidentified "A frog, toad or newt, species unclear"
* #heard "Heard"
* #seen "Seen"
* #none "None heard or seen"
* #not_sure "Not sure"
// --- AI assistance and the citizen's decision
* #ai-suggestion "AI suggestion" "The label an AI provider suggested. The citizen's own answer is the Observation value."
* #ai-confidence "AI confidence" "Confidence the AI provider reported for its suggestion, 0 to 1."
* #ai-provider "AI provider" "Which provider made the suggestion, e.g. mock (demo AI)."
* #citizen-decision "Citizen decision on the AI suggestion"
* #confirmed "Citizen accepted the AI suggestion"
* #corrected "Citizen changed the AI suggestion"
* #rejected "Citizen rejected the AI suggestion"
* #manual "Citizen answered without AI"
* #expert_review "Flagged for expert review (e.g. implausible by GBIF)"
* #guided-key-result "Guided key result"
// --- risk index parts
* #temperature "Temperature suitability"
* #dry_spell "Dry spell"
* #habitat "Habitat (reliability-weighted stream check)"
* #vector_presence "Vector presence (larvae per dip)"
* #predator_deficit "Predator deficit"
* #host_signal "Dead bird signal"
* #risk-band "Risk band"
* #index-range-low "Index lower bound given missing data"
* #index-range-high "Index upper bound given missing data"
* #site-data-coverage "Share of site factor weight with data"
* #low "Low"
* #moderate "Moderate"
* #high "High"
* #very_high "Very high"
// --- weekly city summary groups
* #sites-assessed "Sites with a risk score this week"
* #sites-alert "Sites at or above the alert threshold"
* #sites-needing-data "Sites flagged as needing a stream check"
* #site "Stream site"
// --- observer calibration tiers
* #new "New observer"
* #calibrated "Calibrated observer"
* #trusted "Trusted observer"
// --- approved actions (ServiceRequest.category)
* #vector-control-visit "Vector control or verification visit"
* #sewage-inspection "Sewage inspection"
* #veterinary-notification "Veterinary notification" "Notify veterinary services of a dead bird report. Routing only: no diagnosis is made or implied."
* #habitat-restoration "Habitat restoration (e.g. riparian vegetation recovery)"
// --- volunteer messages (Communication.category)
* #alert_raised "Your observation helped raise an alert"
* #action_taken "Your observation led to an action"

ValueSet: AquaSentinelFindingStatusVS
Id: aquasentinel-finding-status
Title: "AquaSentinel finding status"
Description: "Citizen findings start as preliminary and are promoted to final after citizen confirmation and reliability weighting."
* ^experimental = true
* $obs-status#preliminary
* $obs-status#final

ValueSet: AquaSentinelOahIndicatorVS
Id: aquasentinel-oah-indicators
Title: "OAH indicators used by AquaSentinel"
Description: "The OAH TemporaryOahSystem indicator codes that AquaSentinel findings map to."
* ^experimental = true
* $oah#diptera
* $oah#birds
* $oah#amphibians
* $oah#hydrology
* $oah#morophology
* $oah#foam
* $oah#macrophytes
* $oah#riparianVegetation

ValueSet: AquaSentinelActionCategoryVS
Id: aquasentinel-action-category
Title: "AquaSentinel approved action categories"
Description: "Kinds of action a city officer can approve. Nothing here is a clinical or veterinary order."
* ^experimental = true
* AquaSentinelCodes#vector-control-visit
* AquaSentinelCodes#sewage-inspection
* AquaSentinelCodes#veterinary-notification
* AquaSentinelCodes#habitat-restoration

ValueSet: AquaSentinelActionStatusVS
Id: aquasentinel-action-status
Title: "AquaSentinel action request status"
Description: "Only approved actions become ServiceRequests; they are active until done."
* ^experimental = true
* http://hl7.org/fhir/request-status#active
* http://hl7.org/fhir/request-status#completed

ValueSet: AquaSentinelMessageKindVS
Id: aquasentinel-message-kind
Title: "AquaSentinel volunteer message kinds"
Description: "Feedback messages to volunteers."
* ^experimental = true
* AquaSentinelCodes#alert_raised
* AquaSentinelCodes#action_taken

ValueSet: AquaSentinelCalibrationTierVS
Id: aquasentinel-calibration-tier
Title: "AquaSentinel observer calibration tier"
Description: "Tier from the calibration round (Cohen kappa against the reference set)."
* ^experimental = true
* AquaSentinelCodes#new
* AquaSentinelCodes#calibrated
* AquaSentinelCodes#trusted

ValueSet: AquaSentinelRiskBandVS
Id: aquasentinel-risk-band
Title: "AquaSentinel risk band"
Description: "Bands of the vector-habitat risk index (config/risk.yaml)."
* ^experimental = true
* AquaSentinelCodes#low
* AquaSentinelCodes#moderate
* AquaSentinelCodes#high
* AquaSentinelCodes#very_high
