"""Weight sensitivity: vary each weight by -50 % and +50 % and report how stable site rankings and alerts are.

Runs on the synthetic Coimbra season with real Open-Meteo weather (synthetic citizen data).
Usage: .venv/bin/python -m analysis.sensitivity
"""

from __future__ import annotations

import copy
from datetime import date
from pathlib import Path
from typing import Any

from scipy.stats import spearmanr
from sqlalchemy.pool import StaticPool
from sqlmodel import Session, SQLModel, create_engine

from api import models  # noqa: F401
from api import seed
from api.risk import factors as f
from api.risk.config import load_config
from api.risk.index import combine
from api.risk.service import compute_city

REPORTS = Path(__file__).resolve().parent.parent / "eval" / "reports"
AS_OF = date(2026, 9, 20)


def scenario_rows() -> list[dict[str, Any]]:
    engine = create_engine("sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool)
    SQLModel.metadata.create_all(engine)
    with Session(engine) as session:
        sites = seed.load_sites()
        seed.seed_sites(session, sites)
        seed.seed_synthetic(session, sites, "CO")
        return compute_city(session, "CO", AS_OF, store=False)


def rescore(rows: list[dict[str, Any]], cfg: dict[str, Any]) -> dict[str, dict[str, Any]]:
    out = {}
    for r in rows:
        factor_list = [f.Factor(x["name"], x["label"], x["value"], x["explanation"]) for x in r["factors"]]
        out[r["site_id"]] = combine(factor_list, cfg)
    return out


def compare(base: dict[str, dict[str, Any]], alt: dict[str, dict[str, Any]]) -> dict[str, float]:
    ids = sorted(base)
    rho = spearmanr([base[i]["total"] for i in ids], [alt[i]["total"] for i in ids]).statistic
    top = lambda d: set(sorted(d, key=lambda i: -d[i]["total"])[:5])  # noqa: E731
    alerts_b = {i for i in ids if base[i]["alert"]}
    alerts_a = {i for i in ids if alt[i]["alert"]}
    union = alerts_b | alerts_a
    return {
        "spearman": float(rho),
        "top5_overlap": len(top(base) & top(alt)) / 5,
        "alert_jaccard": len(alerts_b & alerts_a) / len(union) if union else 1.0,
        "alerts": len(alerts_a),
    }


def main() -> None:
    cfg = load_config()
    rows = scenario_rows()
    base = rescore(rows, cfg)
    lines = []
    for group in ("season_weights", "site_weights"):
        for name in cfg[group]:
            for mult in (0.5, 1.5):
                alt_cfg = copy.deepcopy(cfg)
                alt_cfg[group][name] *= mult
                c = compare(base, rescore(rows, alt_cfg))
                lines.append((name, mult, c))
    worst = min(lines, key=lambda x: x[2]["spearman"])
    REPORTS.mkdir(parents=True, exist_ok=True)
    table = ["| Weight | Change | Spearman rank correlation | Top-5 overlap | Alert set Jaccard | Alerts |", "|---|---|---|---|---|---|"]
    for name, mult, c in lines:
        table.append(f"| {name} | x{mult} | {c['spearman']:.3f} | {c['top5_overlap']:.2f} | {c['alert_jaccard']:.2f} | {c['alerts']} |")
    n_alerts = sum(1 for v in base.values() if v["alert"])
    (REPORTS / "sensitivity.md").write_text("\n".join([
        "# Risk index weight sensitivity",
        "",
        "**Synthetic citizen data** (the labelled synthetic Coimbra season) with **real Open-Meteo weather** for the 14 days to "
        f"{AS_OF.isoformat()}. Generated by `python -m analysis.sensitivity`, config {cfg['fingerprint']}.",
        "",
        f"Baseline: {len(base)} sites, {n_alerts} alerts at threshold {cfg['alert_threshold']}.",
        "",
        "Each weight in config/risk.yaml was halved and then increased by half, one at a time, and every site rescored from the same factor values.",
        "",
        *table,
        "",
        "## Reading it",
        "",
        f"- Lowest rank correlation: {worst[2]['spearman']:.3f} when {worst[0]} is multiplied by {worst[1]}.",
        "- Season weights only change the seasonal multiplier, which is the same for every site in a city, so they cannot reorder sites; they can move sites across the alert threshold.",
        "- Alerts sit close to a fixed threshold, so the alert set is more sensitive than the ranking. The dashboard therefore shows the ranking and each site's range, not only the alert flag.",
        "",
        "## Limits",
        "",
        "- One city, one week, synthetic citizen data. The analysis shows how the formula behaves, not whether the weights are right. Setting weights needs field validation with the OAH research teams.",
        "",
    ]) + "\n", encoding="utf-8")
    print("wrote eval/reports/sensitivity.md")


if __name__ == "__main__":
    main()
